const UPLOAD_URL = process.env.UPLOAD_URL || '';      // 节点或订阅自动上传地址,需填写部署Merge-sub项目后的首页地址,例如：https://merge.ct8.pl
const PROJECT_URL = process.env.PROJECT_URL || '';    // 需要上传订阅或保活时需填写项目分配的url,例如：https://google.com   
const AUTO_ACCESS = process.env.AUTO_ACCESS || false; // false关闭自动保活，true开启,需同时填写PROJECT_URL变量
const FILE_PATH = process.env.FILE_PATH || './tmp';   // 运行目录,sub节点文件保存目录
const SUB_PATH = process.env.SUB_PATH || 'together';       // 订阅路径
const PORT = process.env.SERVER_PORT || process.env.PORT || 8080;  // http服务端口，不用改       
const UUID = process.env.UUID || '1549a96f-aee4-41ef-b68a-f41497bf2716'; // 节点uuid
const NEZHA_SERVER = process.env.NEZHA_SERVER || '92.113.117.22:11520';    // 哪吒v1填写形式: nz.abc.com:8008  哪吒v0填写形式：nz.abc.com    
const NEZHA_PORT = process.env.NEZHA_PORT || '';        // 使用哪吒v1请留空，哪吒v0需填写   
const NEZHA_KEY = process.env.NEZHA_KEY || 'suJ4tGNvpyY3CBpJD1hGLdZpsYTqsk9e';          // 哪吒v1的NZ_CLIENT_SECRET或哪吒v0的agent密钥
const ARGO_DOMAIN = process.env.ARGO_DOMAIN || 'altain.shawroll.qzz.io';      // 固定隧道域名,留空即启用临时隧道    
const ARGO_AUTH = process.env.ARGO_AUTH || 'eyJhIjoiNWNiOGM5MmI3NjZmNjdlZjVhM2I4MTY5MWE4MDI0MzMiLCJ0IjoiYjIwMTM5OGEtYTBlNy00YWNkLTk5NzQtNjBjMzM0MTQwZTYzIiwicyI6Ik5UUXhPRGc0TTJFdFkyUTFOUzAwWmpabUxXRm1ZbVF0WXpGaFpEYzJOREV4TXpRMiJ9';          // 固定隧道密钥json或token,留空即启用临时隧道,json获取地址：https://json.zone.id  
const ARGO_PORT = process.env.ARGO_PORT || 8001;        // 固定隧道端口,使用token需在cloudflare后台设置和这里一致    
const CFIP = process.env.CFIP || 'cf.877774.xyz';       // 节点优选域名或优选ip      
const CFPORT = process.env.CFPORT || 443;               // 节点优选域名或优选ip对应的端口    
const NAME = process.env.NAME || 'Choreo';              // 节点名称   
